name: In a better world
description: Curtis Yu's personal blog
url: http://cuyu.github.io

# Custimized config about personal info.
author:
  name: Curtis Yu
  description: Live for <strong>Gaming Sleeping Coding and Fun</strong>.
  contact:
    email: mailto:icyarm@icloud.com
    github: https://github.com/cuyu

gems: [jekyll-paginate, rouge]

markdown: kramdown

highlighter: rouge

# The excerpt will end when hit this tag
excerpt_separator: <!--break-->

# The link format of each post
permalink: /:categories/:year/:month/:day/:title

# How many articles do you wish to appear on the front page
paginate: 5
paginate_path: "/page:num"

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'create_new_post']
