name: In a better world
description: Curtis Yu's personal blog

# Custimized config about personal info.
author:
  name: Curtis Yu
  email: icyarm@icloud.com
  github: https://github.com/cuyu

gems: [jekyll-paginate]
markdown: kramdown
permalink: /:year/:month/:day/:title
# How many articles do you wish to appear on the front page
paginate: 10
# Use pygments to support code highlight
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
