name: In a better world
description: Curtis Yu's personal blog

# Custimized config about personal info.
author:
  name: Curtis Yu
  email: icyarm@icloud.com
  github: https://github.com/cuyu

gems: [jekyll-paginate, rouge]

markdown: kramdown

highlighter: rouge

permalink: /:categories/:year/:month/:day/:title
# How many articles do you wish to appear on the front page
paginate: 2
paginate_path: "/blog/page:num"

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
