title: CuriousY
name: In a better world
description: Curtis Yu's personal blogging
url: http://cuyu.github.io
tagline: 'A world with wonder'

# Custimized config about personal info.
author:
  name: Curtis Yu
  description: Live for <strong>Gaming Sleeping Coding and Fun</strong>.
  contact:
    email: mailto:icyarm@icloud.com
    github: https://github.com/cuyu
    stack-overflow: http://stackoverflow.com/users/5996843

gems: [jekyll-paginate, rouge]

markdown: kramdown

highlighter: rouge

# The excerpt will end when hit this tag
excerpt_separator: <!--break-->

# The link format of each blogging
permalink: /:categories/:year/:month/:day/:title

# How many articles do you wish to appear on the front page
paginate: 5
paginate_path: "/page:num"

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'blogging', '_drafts']

version: 1.0.0