#!/usr/bin/env python
# -*- coding: utf-8 -*-
import argparse
import os
import datetime
from subprocess import call
from termcolor import colored
from tabulate import tabulate
from pprint import pprint
import codecs

THIS_FILE_DIR = os.path.split(os.path.abspath(__file__))[0]


def _list_meta_info():
    result = dict()
    categories = dict()
    tags = dict()
    result['category'] = categories
    result['tag'] = tags
    for file_name in os.listdir(os.path.join(THIS_FILE_DIR, '_posts')):
        with codecs.open(os.path.join(THIS_FILE_DIR, '_posts', file_name), 'r', encoding='utf-8') as f:
            f.readline()
            while True:
                line = f.readline()
                if line.startswith('category:'):
                    category = line[9:].strip()
                    if category in categories:
                        categories[category] += 1
                    else:
                        categories[category] = 1
                if line.startswith('tags:'):
                    tag_list = line[5:].strip()[1:-1].split(',')
                    for tag in tag_list:
                        tag = tag.strip()
                        if tag in tags:
                            tags[tag] += 1
                        else:
                            tags[tag] = 1
                if line == '---\n':
                    break
    return result


def stats_categories():
    result = _list_meta_info()
    table = []
    all_categories =  result['category'].keys()
    all_categories.sort()
    for c in all_categories:
        table.append([c, result['category'][c]])
    print tabulate(table, headers=['Category', 'Count'])


def stats_tags():
    result = _list_meta_info()
    table = []
    all_tags = result['tag'].keys()
    all_tags.sort()
    for c in all_tags:
        table.append([c, result['tag'][c]])
    print tabulate(table, headers=['Tag', 'Count'])


if __name__ == '__main__':
    parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter,
                                     description='A simple tool to create new blogging file.\n' +
                                                 'Use example: ./blogging new "post_title" category tag1,tag2\n')
    subparsers = parser.add_subparsers(help='Use {subcommand} -h for each subcommand\'s optional arguments details',
                                       dest='command')
    create_parser = subparsers.add_parser('new', help='Create new blogging')
    create_parser.add_argument('post_title', help='Title of the blogging blogging')
    create_parser.add_argument('category', help='The category of the blogging')
    create_parser.add_argument('tags', help='The tag list of the blogging, split by comma')

    ls_parser = subparsers.add_parser('ls', help='List exist stats')
    ls_parser.add_argument('list_content', choices=['categories', 'tags'])

    args = parser.parse_args()

    if args.command == 'new':
        post_name = args.post_title
        post_words = post_name.split(' ')
        post_tags = '[' + ', '.join(args.tags.split(',')) + ']'
        today = datetime.date.today()
        file_name = str(today)
        for word in post_words:
            file_name += '-' + word
        file_name += '.md'
        content = """---
layout: post
title: "{title}"
category: {category}
tags: {tags}
date: {date}
---""".format(title=post_name, date=str(today), category=args.category, tags=post_tags)

        post_path = os.path.join(THIS_FILE_DIR, '_posts', '{0}'.format(file_name))
        with open(post_path, 'w') as f:
            f.write(content)
        print "\"{0}\" has been created under _posts folder.".format(file_name)
        call(['open', post_path])
    elif args.command == 'ls':
        if args.list_content == 'categories':
            stats_categories()
        elif args.list_content == 'tags':
            stats_tags()
